<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Hima-PC" failures="2" tests="2" name="Default test(failed)" time="0.057" errors="0" timestamp="19 May 2020 15:16:23 GMT">
  <testcase classname="testpackage.TestNg_RetryFailDemo" name="test3" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testpackage.TestNg_RetryFailDemo.test3(TestNg_RetryFailDemo.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="testpackage.TestNg_RetryFailDemo" name="test2" time="0.003">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at testpackage.TestNg_RetryFailDemo.test2(TestNg_RetryFailDemo.java:16)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed) -->
